import { Manrope, Montserrat } from "next/font/google";

import { AppProvider } from "@/src/app/providers";

import type { Metadata } from "next";

import "@src/app/styles/style.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["cyrillic", "latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${manrope.variable} ${montserrat.variable}`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
